# Generated by Django 3.2.4 on 2021-06-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('time_to_cook', models.SmallIntegerField(db_index=True, default=0, verbose_name='Время приготовления')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('count', models.SmallIntegerField(db_index=True, default=0, verbose_name='Количество порций')),
                ('body', models.TextField(blank=True, db_index=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
