# Generated by Django 4.0.4 on 2022-05-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210707_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('age', models.SmallIntegerField(db_index=True, default=0, null=True, verbose_name='Возраст')),
                ('сity', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Город')),
                ('status', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=250, verbose_name='Тэги')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.viewdish', verbose_name='Вид блюда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.people', verbose_name='Комментаторы')),
                ('tag_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tags', verbose_name='Теги')),
            ],
        ),
    ]
